require 'pry'
require 'nokogiri'
require 'open-uri'
require 'sqlite3'
require 'erb'
require_relative '../lib/models/studentsitescraper.rb'
require_relative '../lib/models/studentscraper.rb'
require_relative '../lib/models/student.rb'
require_relative '../lib/models/cli.rb'
# require_relative '../bin/generate.rb'
# require_relative '../bin/generate_run.rb'
